name: YouTube Link Extractor with Selenium
on: [workflow_dispatch]

jobs:
  selenium:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install selenium webdriver-manager
          sudo apt-get install -y chromium-browser chromium-chromedriver

      - name: Run Selenium Script
        run: |
          python <<EOF
          from selenium import webdriver
          from selenium.webdriver.chrome.options import Options
          from webdriver_manager.chrome import ChromeDriverManager

          # Konfigurasi ChromeOptions
          options = Options()
          options.add_argument("--headless")
          options.add_argument("--no-sandbox")
          options.add_argument("--disable-dev-shm-usage")
          options.add_argument("--disable-gpu")
          options.add_argument("user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36")

          # Inisialisasi WebDriver (HANYA gunakan parameter options)
          driver = webdriver.Chrome(options=options)
          
          try:
              driver.get("https://youtu.be/OIlWZhB3Ag0")
              print("URL setelah render:", driver.current_url)
          finally:
              driver.quit()
          EOF
