name: Get YouTube Stream URL (Stable Version)
on:
  workflow_dispatch:
    inputs:
      video_id:
        description: 'YouTube Video ID (contoh: OIlWZhB3Ag0)'
        required: true
        default: 'OIlWZhB3Ag0'

jobs:
  get-stream-url:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq curl

      - name: Try Piped API (Primary)
        id: piped_api
        continue-on-error: true
        run: |
          INSTANCE="https://piped.privacydev.net"
          RESPONSE=$(curl -s -m 10 "$INSTANCE/streams/${{ inputs.video_id }}")
          
          if echo "$RESPONSE" | jq -e '.videoStreams[0].url' >/dev/null; then
            URL=$(echo "$RESPONSE" | jq -r '.videoStreams[0].url')
            echo "::set-output name=stream_url::${URL}"
            echo "Success using Piped: ${URL}"
          else
            echo "Piped API failed"
            exit 1
          fi

      - name: Try Invidious API (Fallback)
        if: steps.piped_api.outcome == 'failure'
        id: invidious_api
        continue-on-error: true
        run: |
          INSTANCE="https://inv.odyssey346.dev"
          RESPONSE=$(curl -s -m 10 "$INSTANCE/api/v1/videos/${{ inputs.video_id }}")
          
          if echo "$RESPONSE" | jq -e '.formatStreams[0].url' >/dev/null; then
            URL=$(echo "$RESPONSE" | jq -r '.formatStreams[0].url')
            echo "::set-output name=stream_url::${URL}"
            echo "Success using Invidious: ${URL}"
          else
            echo "Invidious API failed"
            exit 1
          fi

      - name: Final Fallback (Direct Parse)
        if: steps.invidious_api.outcome == 'failure'
        run: |
          echo "::error::All API methods failed. Try these manual solutions:"
          echo "1. Use yt-dlp locally: yt-dlp -g https://youtu.be/${{ inputs.video_id }}"
          echo "2. Check instance status at https://api.invidious.io"
          exit 1

      - name: Show Result
        if: success()
        run: |
          echo "Stream URL: ${{ steps.piped_api.outputs.stream_url || steps.invidious_api.outputs.stream_url }}"
