name: Get YouTube Stream URL via Piped API
on:
  workflow_dispatch:
    inputs:
      video_id:
        description: 'YouTube Video ID (contoh: OIlWZhB3Ag0)'
        required: true
        default: 'OIlWZhB3Ag0'

jobs:
  get-stream-url:
    runs-on: ubuntu-latest
    steps:
      - name: Get Stream URL
        id: extract_url
        run: |
          # Daftar instance Piped alternatif
          INSTANCES=(
            "https://piped.kavin.rocks"
            "https://piped.video"
            "https://piped.tokhmi.xyz"
          )
          
          for instance in "${INSTANCES[@]}"; do
            echo "Mencoba instance: $instance"
            URL=$(curl -s "$instance/streams/${{ inputs.video_id }}" | jq -r '.videoStreams[0].url? // empty')
            
            if [ -n "$URL" ]; then
              echo "::set-output name=stream_url::${URL}"
              echo "Berhasil! Link: ${URL}"
              break
            fi
          done

          if [ -z "$URL" ]; then
            echo "::error::Semua instance gagal"
            exit 1
          fi

      - name: Show Result
        run: |
          echo "Link streaming: ${{ steps.extract_url.outputs.stream_url }}"
