name: Get YouTube Stream URL via Invidious
on:
  workflow_dispatch:
    inputs:
      video_id:
        description: 'YouTube Video ID (contoh: OIlWZhB3Ag0)'
        required: true
        default: 'OIlWZhB3Ag0'

jobs:
  get-stream-url:
    runs-on: ubuntu-latest
    steps:
      - name: Get Stream URL
        id: get_url
        run: |
          # Daftar instance Invidious alternatif
          INSTANCES=(
            "https://invidious.nerdvpn.de"
            "https://yt.artemislena.eu"
            "https://invidious.slipfox.xyz"
          )

          for instance in "${INSTANCES[@]}"; do
            echo "Mencoba instance: $instance"
            URL=$(curl -s "$instance/api/v1/videos/${{ inputs.video_id }}" | jq -r '.formatStreams[0].url? // empty')
            
            if [ -n "$URL" ]; then
              echo "::set-output name=stream_url::${URL}"
              echo "Berhasil! Link: ${URL}"
              exit 0
            fi
          done

          echo "::error::Semua instance gagal"
          exit 1

      - name: Show Result
        run: |
          echo "Link streaming: ${{ steps.get_url.outputs.stream_url }}"
