name: Simple YouTube Link Extractor
on: [workflow_dispatch]

jobs:
  get-link:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup yt-dlp
        run: |
          pip install yt-dlp
          yt-dlp --version

      - name: Extract URL
        run: |
          yt-dlp \
            --user-agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64)" \
            --referer "https://youtube.com" \
            --no-check-certificate \
            -g "https://youtu.be/OIlWZhB3Ag0"
