name: Get YouTube Stream Link via Piped
on: 
  workflow_dispatch:
    inputs:
      video_id:
        description: 'YouTube Video ID'
        required: true
        default: 'OIlWZhB3Ag0'

jobs:
  get-link:
    runs-on: ubuntu-latest
    steps:
      - name: Get Stream URL
        run: |
          VIDEO_ID="${{ inputs.video_id }}"
          STREAM_URL=$(curl -s "https://piped.kavin.rocks/streams/${VIDEO_ID}" | jq -r '.videoStreams[0].url')
          echo "::set-output name=stream_url::${STREAM_URL}"
          echo "Stream URL: ${STREAM_URL}"
